name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  - name: TestProjects
    value: "tests/**/*Tests.csproj"
  - name: RestoreBuildProjects
    value: "Veso.Server/Veso.Server.csproj"
  - name: DotNetSdkVersion
    value: 3.1.100

pr:
  autoCancel: true

trigger:
  batch: true

jobs:
  - template: azure-pipelines-main.yml
    parameters:
      LinuxImage: "ubuntu-latest"
      RestoreBuildProjects: $(RestoreBuildProjects)

  - template: azure-pipelines-test.yml
    parameters:
      ImageNames:
        Linux: "ubuntu-latest"
        Windows: "windows-latest"
        macOS: "macos-latest"

  - template: azure-pipelines-windows.yml
    parameters:
      WindowsImage: "windows-latest"
      TestProjects: $(TestProjects)

  - template: azure-pipelines-compat.yml
    parameters:
      Packages:
        Naming:
          NugetPackageName: Veso.Naming
          AssemblyFileName: Emby.Naming.dll
        Controller:
          NugetPackageName: Veso.Controller
          AssemblyFileName: MediaBrowser.Controller.dll
        Model:
          NugetPackageName: Veso.Model
          AssemblyFileName: MediaBrowser.Model.dll
        Common:
          NugetPackageName: Veso.Common
          AssemblyFileName: MediaBrowser.Common.dll
      LinuxImage: "ubuntu-latest"
