name: Release-$(Version)-$(date:yyyyMMdd).$(rev:r)

variables:
  - name: Version
    value: '1.0.0'
  - name: UsedRunId
    value: 0

trigger: none
pr: none

jobs:
  - job: publish_artifacts_release
    displayName: Publish Artifacts Release
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: none
    - task: DownloadPipelineArtifact@2
      displayName: Download the Windows Setup Artifact
      inputs:
        source: 'specific' # Options: current, specific
        artifact: 'Veso Server Setup' # Optional
        path: '$(System.ArtifactsDirectory)/win-installer'
        project: '$(System.TeamProjectId)' # Required when source == Specific
        pipelineId: 1 # Required when source == Specific
        runVersion: 'specific' # Required when source == Specific. Options: latest, latestFromBranch, specific
        runId: $(UsedRunId)

    - task: SSH@0
      displayName: 'Create Drop directory'
      inputs:
        sshEndpoint: 'Veso Build Server'
        commands: 'mkdir -p /srv/incoming/veso_$(Version)/win-installer && ln -s /srv/incoming/veso_$(Version) /srv/incoming/veso_release_azure_upload'

    - task: CopyFilesOverSSH@0
      displayName: 'Copy the Windows Setup to the Repo'
      inputs:
        sshEndpoint: 'Veso Build Server'
        sourceFolder: '$(System.ArtifactsDirectory)/win-installer'
        contents: 'veso_*.exe'
        targetFolder: '/srv/incoming/veso_release_azure_upload/win-installer'

    - task: SSH@0
      displayName: 'Clean up SCP symlink'
      inputs:
        sshEndpoint: 'Veso Build Server'
        commands: 'rm -f /srv/incoming/veso_release_azure_upload'
